- stage: app_deployment
  displayName: App Deployment
  dependsOn: [ infra_deployment ]
  condition: and( succeeded('infra_deployment'), or(eq(variables.isDevelop, true), eq(variables.isRelease, true), eq(variables.isMaster, true)))
  variables:
    - group: ${{ variables.ENV_NAME }}
  jobs:
    - job: app_deployment
      displayName: Azure Static Web App Tools
      steps:
        - task: UseNode@1
          inputs:
            version: '$(NODE_VERSION)'
          displayName: 'Install Node.js'
        - script: rm .env
          displayName: Remove .env file
        - script: npm install
          displayName: 'npm install'
        - script: npm install -g @azure/static-web-apps-cli
          displayName: 'npm install swa'
        - script: npm run build
          displayName: 'npm run build'
        - task: AzureCLI@2
          displayName: Deploy Static Web App
          env:
            RESOURCE_GROUP_NAME: ${{ lower(variables['REPO_PROJECT']) }}-${{ lower(variables['APP_NAME']) }}-${{ lower(variables['ENV_NAME']) }}-${{ lower(variables['LOCATION_SHORT']) }}-${{ lower(variables['COUNTER']) }}
          inputs:
            azureSubscription: $(SERVICE_CONNECTION)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: swa deploy --env production --app-name $RESOURCE_GROUP_NAME --resource-group $RESOURCE_GROUP_NAME