############## Created by de.microtema:azure-devops-pipelines-maven-plugin ############
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# File azure-pipelines.yaml is generated and should not be edited. #
################################################################################

trigger: [%TRIGGERS%]

pool:
  vmImage: ubuntu-latest
variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    ENV_NAME: "DEV"
    SERVICE_CONNECTION: "PROJECT_NAME_SUBSCRIPTION_DEV"
  ${{ elseif startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    ENV_NAME: "INT"
    SERVICE_CONNECTION: "PROJECT_NAME_SUBSCRIPTION_INT"
  ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    ENV_NAME: "PRD"
    SERVICE_CONNECTION: "PROJECT_NAME_SUBSCRIPTION_PRD"
  ${{ else }}:
    ENV_NAME: "DEV"
    SERVICE_CONNECTION: "PROJECT_NAME_SUBSCRIPTION_DEV"
%VARIABLES%

stages:
%STAGES%
