############## Created by de.microtema:azure-devops-pipelines-maven-plugin ############
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# File azure-pipelines.yaml is generated and should not be edited. #
################################################################################

trigger: [%TRIGGERS%]

pool:
  vmImage: ubuntu-latest

%VARIABLES%
  
stages:
%STAGES%
