############## Created by de.microtema:azure-devops-pipelines-maven-plugin ############
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
# azure-pipelines.yml is generated and should not be edited. #
################################################################################

trigger: [%TRIGGER%]

%VARIABLES%
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    STAGE_NAME: "DEV"
  ${{ elseif startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    STAGE_NAME: "INT"
  ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    STAGE_NAME: "PROD"
  ${{ else }}:
    STAGE_NAME: "DEV"

stages:
%STAGES%
