- stage: deployment
  displayName: Deployment
  dependsOn: [ db_migration ]
  condition: succeeded('db_migration')
  jobs:
    - job: deployment
      displayName: Deployment
      pool:
        vmImage: ubuntu-latest
      steps:
        - script: echo deployment
          displayName: 'Run a one-line script'